title: Revati Thatte
author: Revati Thatte
email: thatte.revati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is my personal website what up fools

# social links
twitter_username: revthat # DO NOT include the @ character, or else the build will fail!
github_username:  revthat # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
